name: py3.8
channels:
  - pytorch
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.12=h4ab18f5_0
  - aom=3.9.1=hac33072_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.34.2=heb4867d_0
  - ca-certificates=2024.8.30=hbcca054_0
  - cairo=1.18.0=hebfffa5_3
  - comm=0.2.1=pyhd8ed1ab_0
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - decorator=5.1.1=pyhd8ed1ab_0
  - double-conversion=3.3.0=h59595ed_0
  - expat=2.6.3=h5888daf_0
  - ffmpeg=6.1.2=gpl_h3e00e3c_103
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.13=h59595ed_1003
  - harfbuzz=9.0.0=hda332d3_1
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - icu=75.1=he02047a_0
  - imath=3.1.12=h7955e40_0
  - importlib_metadata=7.0.1=hd8ed1ab_0
  - jasper=4.2.4=h536e39c_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.7.1=py38h578d9bd_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.2=cxx17_he02047a_1
  - libaec=1.1.3=h59595ed_0
  - libasprintf=0.22.5=he8f35ee_3
  - libass=0.17.3=h1dc1e6a_0
  - libblas=3.9.0=25_linux64_openblas
  - libcblas=3.9.0=25_linux64_openblas
  - libclang-cpp19.1=19.1.2=default_hb5137d0_1
  - libclang13=19.1.2=default_h9c6a7e4_1
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.10.1=hbbe4b11_0
  - libdeflate=1.22=hb9d3cd8_0
  - libdrm=2.4.123=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libegl=1.7.0=ha4b6fd6_1
  - libev=4.33=hd590300_2
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgl=1.7.0=ha4b6fd6_1
  - libglib=2.82.2=h2ff4ddf_0
  - libglu=9.0.0=ha6d2627_1004
  - libglvnd=1.7.0=ha4b6fd6_1
  - libglx=1.7.0=ha4b6fd6_1
  - libgomp=14.2.0=h77fa898_1
  - libhwloc=2.11.1=default_hecaa2ac_1000
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=25_linux64_openblas
  - liblapacke=3.9.0=25_linux64_openblas
  - libllvm19=19.1.2=ha7bfdaf_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.4=h7f98852_1002
  - libopenblas=0.3.28=pthreads_h94d23a6_0
  - libopencv=4.10.0=qt6_py38h3839c77_603
  - libopenvino=2024.3.0=h2da1b83_0
  - libopenvino-auto-batch-plugin=2024.3.0=hb045406_0
  - libopenvino-auto-plugin=2024.3.0=hb045406_0
  - libopenvino-hetero-plugin=2024.3.0=h5c03a75_0
  - libopenvino-intel-cpu-plugin=2024.3.0=h2da1b83_0
  - libopenvino-intel-gpu-plugin=2024.3.0=h2da1b83_0
  - libopenvino-intel-npu-plugin=2024.3.0=h2da1b83_0
  - libopenvino-ir-frontend=2024.3.0=h5c03a75_0
  - libopenvino-onnx-frontend=2024.3.0=h07e8aee_0
  - libopenvino-paddle-frontend=2024.3.0=h07e8aee_0
  - libopenvino-pytorch-frontend=2024.3.0=he02047a_0
  - libopenvino-tensorflow-frontend=2024.3.0=h39126c6_0
  - libopenvino-tensorflow-lite-frontend=2024.3.0=he02047a_0
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.44=hadc24fc_0
  - libpq=17.0=h04577a9_4
  - libprotobuf=4.25.3=hd5b35b9_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.47.0=hadc24fc_1
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtiff=4.7.0=he137b08_1
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h8a09558_1
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h2c5496b_1
  - libxml2=2.12.7=he7c6b58_4
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mysql-common=9.0.1=h266115a_2
  - mysql-libs=9.0.1=he0572af_2
  - ncurses=6.5=he02047a_1
  - numpy=1.24.4=py38h59b608b_0
  - ocl-icd=2.3.2=hd590300_1
  - opencv=4.10.0=qt6_py38h994133a_603
  - openexr=3.2.2=h04e0de5_2
  - openh264=2.4.1=h59595ed_0
  - openldap=2.6.8=hedd0468_0
  - openssl=3.3.2=hb9d3cd8_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre2=10.44=hba22ea6_2
  - pickleshare=0.7.5=py_1003
  - pixman=0.43.2=h59595ed_0
  - prompt_toolkit=3.0.42=hd8ed1ab_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pugixml=1.14=h59595ed_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-opencv=4.10.0=qt6_py38h5776979_603
  - python=3.8.20=h4a871b0_2_cpython
  - python_abi=3.8=4_cp38
  - qt6-main=6.7.3=h6e8976b_1
  - readline=8.2=h8228510_1
  - setuptools=69.1.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.1=ha2e4443_0
  - sqlite=3.47.0=h9eae976_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - svt-av1=2.2.1=h5888daf_0
  - tbb=2021.13.0=h84d6215_0
  - tk=8.6.13=noxft_h4845f30_101
  - traitlets=5.14.1=pyhd8ed1ab_0
  - typing_extensions=4.10.0=pyha770c72_0
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.37=hd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xorg-libice=1.1.1=hb9d3cd8_1
  - xorg-libsm=1.2.4=he73a12e_1
  - xorg-libx11=1.8.10=h4f16b4b_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.2=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.11=hb9d3cd8_1
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.5=hb9d3cd8_4
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.5=h59595ed_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
    - addict==2.4.0
    - annotated-types==0.7.0
    - ansitable==0.11.2
    - apptools==5.3.0
    - asttokens==2.1.0
    - astunparse==1.6.3
    - attrs==23.2.0
    - bokeh==3.1.1
    - casadi==3.7.0
    - catkin-pkg==1.0.0
    - certifi==2024.2.2
    - cfgv==3.4.0
    - charset-normalizer==3.3.2
    - click==8.1.3
    - colorama==0.4.6
    - colored==1.4.4
    - commonmark==0.9.1
    - configargparse==1.5.3
    - configobj==5.0.9
    - contourpy==1.0.6
    - cycler==0.12.1
    - cython==3.0.10
    - dash==2.7.0
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - debugpy==1.6.3
    - deformable-control==0.1.0
    - dill==0.3.6
    - distlib==0.3.8
    - distro==1.9.0
    - do-mpc==4.6.5
    - docutils==0.20.1
    - entrypoints==0.4
    - envisage==7.0.3
    - executing==1.2.0
    - fastjsonschema==2.16.2
    - filelock==3.15.4
    - flask==2.2.2
    - fonttools==4.38.0
    - gmsh==4.12.2
    - helpers==0.2.0
    - identify==2.6.0
    - idna==3.7
    - imageio==2.34.1
    - importlib-metadata==5.0.0
    - importlib-resources==5.10.0
    - install==1.3.5
    - ipyevents==2.0.2
    - ipykernel==6.17.1
    - ipython==8.6.0
    - ipywidgets==8.0.2
    - itsdangerous==2.1.2
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyter-client==7.4.7
    - jupyterlab-widgets==3.0.3
    - kiwisolver==1.4.4
    - lazy-loader==0.4
    - line-profiler==4.1.3
    - markdown==3.7
    - markupsafe==2.1.1
    - math3d==3.4.1
    - matplotlib==3.7.5
    - mayavi==4.8.2
    - meshio==5.3.4
    - meshtaichi-patcher==0.0.19
    - more-itertools==10.5.0
    - msgpack==1.1.0
    - nbformat==5.5.0
    - nest-asyncio==1.5.6
    - nodeenv==1.9.1
    - onnx==1.16.0
    - open3d==0.16.0
    - opencv-python==4.9.0.80
    - packaging==21.3
    - pandas==2.0.3
    - panel==1.2.3
    - param==2.1.1
    - patsy==1.0.1
    - pexpect==4.8.0
    - pillow==10.4.0
    - pip==24.2
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.2.2
    - plotly==5.24.1
    - pooch==1.8.2
    - pre-commit==3.5.0
    - prompt-toolkit==3.0.33
    - protobuf==5.26.1
    - psutil==5.9.4
    - pybullet==3.2.5
    - pydantic==2.9.2
    - pydantic-core==2.23.4
    - pyface==8.0.0
    - pygal==3.0.5
    - pygame==2.5.2
    - pygments==2.13.0
    - pygmsh==7.1.17
    - pyk4a==1.5.0
    - pyopengl==3.1.7
    - pyparsing==3.0.9
    - pyqt5==5.15.11
    - pyqt5-qt5==5.15.15
    - pyqt5-sip==12.15.0
    - pyquaternion==0.9.9
    - pyrsistent==0.19.2
    - python-dateutil==2.8.2
    - pytz==2022.6
    - pyvista==0.44.1
    - pyviz-comms==3.0.3
    - pywavefront==1.3.3
    - pyyaml==6.0
    - pyzed==4.1
    - pyzmq==24.0.1
    - qtm-rt==3.0.1
    - referencing==0.34.0
    - requests==2.32.3
    - rich==12.6.0
    - rospkg==1.4.0
    - rpds-py==0.18.0
    - scikit-image==0.21.0
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - scooby==0.10.0
    - seaborn==0.13.2
    - shapely==2.0.7
    - sort-vertices==0.0.0
    - sourceinspect==0.0.4
    - spatialmath-python==1.1.11
    - stack-data==0.6.1
    - statsmodels==0.14.1
    - style==1.1.0
    - taichi==1.6.0
    - tenacity==8.1.0
    - threadpoolctl==3.1.0
    - tornado==6.2
    - tqdm==4.64.1
    - traits==6.4.3
    - traitsui==8.0.0
    - trame==3.6.5
    - trame-client==3.3.2
    - trame-server==3.2.3
    - typing-extensions==4.4.0
    - tzdata==2024.1
    - update==0.0.1
    - urllib3==2.2.3
    - urx==0.11.0
    - virtualenv==20.26.3
    - vtk==9.3.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.2.2
    - widgetsnbextension==4.0.3
    - wslink==2.2.1
    - xyzservices==2024.9.0
    - zipp==3.10.0
prefix: /home/yiliao/anaconda3/envs/py3.8
